package com.directinsuranceexercise.rest.model;

import jakarta.validation.constraints.NotEmpty;

public abstract class GenericAdvertisement {
    @AutoGenerated
    protected long id;

    @NotEmpty
    private String adType;

    protected Integer price;

    private String contactPhoneNumber;
    private String contactName;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }


    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public String getContactPhoneNumber() {
        return contactPhoneNumber;
    }

    public void setContactPhoneNumber(String contactPhoneNumber) {
        this.contactPhoneNumber = contactPhoneNumber;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getAdType() {
        return adType;
    }

    public void setAdType(String adType) {
        this.adType = adType;
    }

}
